// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wire

import (
	"asong.cloud/Golang_Dream/code_demo/go-elastic-asong/common"
	"asong.cloud/Golang_Dream/code_demo/go-elastic-asong/config"
	"asong.cloud/Golang_Dream/code_demo/go-elastic-asong/dao"
	"asong.cloud/Golang_Dream/code_demo/go-elastic-asong/handler"
	"asong.cloud/Golang_Dream/code_demo/go-elastic-asong/service"
)

// Injectors from wire.go:

func InitializeHandler(conf *config.ServerConfig) *handler.UserHandler {
	engine := common.NewRouterClient()
	client := common.NewEsClient(conf)
	userES := dao.NewUserES(client)
	userService := service.NewUserService(userES)
	userHandler := handler.NewUserHandler(engine, userService)
	return userHandler
}
