// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wire

import (
	"asong.cloud/Golang_Dream/wire_cron_example/config"
	"asong.cloud/Golang_Dream/wire_cron_example/cron"
	"asong.cloud/Golang_Dream/wire_cron_example/cron/task"
	"asong.cloud/Golang_Dream/wire_cron_example/dao"
	"asong.cloud/Golang_Dream/wire_cron_example/service"
)

// Injectors from wire.go:

func InitializeCron(mysql *config.Mysql) *cron.Cron {
	db := dao.NewClientDB(mysql)
	userDB := dao.NewUserDB(db)
	userService := service.NewUserService(userDB)
	scanner := task.NewScanner(userService)
	cronCron := cron.NewCron(scanner)
	return cronCron
}
